-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 08:52:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AutoBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AutoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AutoBD` DEFAULT CHARACTER SET utf8 ;
USE `AutoBD` ;

-- -----------------------------------------------------
-- Table `AutoBD`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AutoBD`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `AutoBD`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `DOB` VARCHAR(45) NOT NULL,
  `idAdresse` INT,
  `NumPermis` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
   CONSTRAINT `fk_Utilisateur_Adresse1`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `autobd`.`Adresse` (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AutoBD`.`Voiture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AutoBD`.`Voiture` ;

CREATE TABLE IF NOT EXISTS `AutoBD`.`Voiture` (
  `idVoiture` INT NOT NULL,
  `Marque` VARCHAR(45) NOT NULL,
  `Modele` VARCHAR(45) NOT NULL,
  `Transmission` VARCHAR(45) NOT NULL,
  `Carburant` VARCHAR(45) NOT NULL,
  `Passager` INT(5) NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idVoiture`),
  INDEX `fk_Voiture_Utilisateur1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Voiture_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `autobd`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AutoBD`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AutoBD`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `AutoBD`.`Adresse` (
  `idAdresse` INT NOT NULL,
  `NumeroCivique` INT NOT NULL,
  `Rue` VARCHAR(45) NOT NULL,
  `CodePostal` VARCHAR(45) NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  `Province` VARCHAR(45) NOT NULL,
  `Pays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresse`)
  
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AutoBD`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AutoBD`.`Location` ;

CREATE TABLE IF NOT EXISTS `AutoBD`.`Location` (
  `idLocation` INT NOT NULL,
  `dateLocation` DATE NOT NULL,
  `idVoiture` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `idVoiture`, `idUtilisateur`),
  INDEX `fk_Location_Voiture_idx` (`idVoiture` ASC) VISIBLE,
  INDEX `fk_Location_Utilisateur1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Voiture`
    FOREIGN KEY (`idVoiture`)
    REFERENCES `AutoBD`.`Voiture` (`idVoiture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `AutoBD`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Utilisateur (idUtilisateur, Nom, Prenom, DOB, NumPermis, Username, Password, Type, idAdresse)
VALUES
(1, 'Tremblay', 'Paul', '19-02-1999', 'R7777-90933-09','Paulo999','ALLO90988', 'Client', 1),
(2, 'Dugas', 'Pierre', '12-02-1989', 'O677-93233-01','Elvis890','ONNDFS888', 'Client', 2),
(3, 'Legros', 'Phil', '01-01-1990', 'L90987-92330-09','LaprisePlug78','KMSAODISA78', 'Proprio', 3),
(4, 'Roy', 'Jean', '21-01-1988', 'P90984-090876-09','AOPPP999','PSADKASOP', 'Client', 4);

INSERT INTO Voiture (idVoiture, Marque, Modele, Transmission, Carburant, Passager, idUtilisateur)
VALUES
(1, 'Hyundai', 'Elantra', 'Automatique', 'Gaz', '5', 3),
(2, 'Hyundai', 'Sonata', 'Automatique', 'Gaz', '5', 3),
(3, 'Hyundai', 'Tucson', 'Automatique', 'Gaz', '5', 3),
(4, 'Hyundai', 'Kona', 'Automatique', 'Gaz', '5', 3);

INSERT INTO Location (idLocation, dateLocation, idVoiture, idUtilisateur)
VALUES
(1,'2022-02-19', 2, 1);

INSERT INTO Adresse (idAdresse, NumeroCivique, Rue, CodePostal, Ville, Province, Pays)
VALUES
(1, 2490, 'rue Parthenais', 'H2K3R3', 'Montreal', 'Quebec', 'Canada'),
(2, 4685, 'rue Legault', 'H2K7D8', 'Montreal', 'Quebec', 'Canada'),
(3, 9049, 'rue Masson', 'S8H8B9', 'Montreal', 'Quebec', 'Canada'),
(4, 1902, 'rue Leblanc', 'E4Y6G7', 'Montreal', 'Quebec', 'Canada');

